INSERT INTO biobank_dev.list_pi (PI_name) VALUES
	 (NULL),
	 ('Montplaisir, Jacques'),
	 ('Warby, Simon'),
	 ('Blanchet, Pierre'),
	 ('Gosselin, Nadia'),
	 ('Gagnon, Jean-François'),
	 ('Carrier, Julie'),
	 ('Desautels, Alex'),
	 ('Nielsen, Tore'),
	 ('Zadra, Antonio'),
	 ('Ayas, Najib'),
	 ('Hanly, Pat'),
	 ('Skomro, Rob'),
	 ('Narang, Indra'),
	 ('Katz, Sherri'),
	 ('De Beaumont, Louis'),
	 ('Dumont, Marie'),
	 ('Dauvilliers, Yves'),
	 ('Kimoff, John'),
	 ('Sériès, Frédéric'),
	 ('Robillard, Rebecca'),
	 ('Bastien, Célyne'),
	 ('Hudon, Carol'),
	 ('Lorrain, Dominique'),
	 ('Postuma, Ron');
